### ISSUE TITLE
Conda collections not available for Mac OSX

### ISSUE THREAD

**Issue by guillermo-carrasco** [chapmanb/bcbio-nextgen-vm#10]
Not sure if you want to support that, but the builds seem to be only available for linux-64, so when you try to run the installer on a Mac system, this is what you get:

```
(master)guillem@Guillermos-MacBook-Air-2:~/bcbio-docker$ conda install --yes -c https://conda.binstar.org/collections/chapmanb bcbio-nextgen-vm
Error: HTTPError: 404  NOT FOUND  https://conda.binstar.org/collections/chapmanb/osx-64/
```

I'll have a look and try to build the packages for MacOSx

**Comment by chapmanb** [comment]
Guillermo;
We fully support Mac OSX conda packages for bcbio and bcbio-vm now and will keep them up to date with new releases. `conda convert` allows us to make OSX packages for the regularly changing bcbio conda releases, since they are python-only. We'll manually re-create Mac OSX packages for any new dependency releases with C extensions, since those are infrequent. We're still working on supporting Docker runs on OSX, and I've detailed the current status in the README. Happy to have help or suggestions on the Docker part from any Mac/Docker experts. Thanks much.

**Comment by guillermo-carrasco** [comment]
Hi Brad, 

Really appreciate this work, thanks you very much! And sorry for not having contributed as I would have liked to :-/

As soon as I can I'll try to deploy bcbio-nextgen on my mac and let you guys know if I encounter problems. 

Thanks again!
